In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv('drug200.csv')

In [13]:
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [41]:
type(final_data['Sex_M'][0])

numpy.uint8

In [38]:
final_data.columns

Index(['Age', 'Na_to_K', 'Drug', 'Sex_M', 'BP_LOW', 'BP_NORMAL',
       'Cholesterol_NORMAL'],
      dtype='object')

In [57]:
cols=['Sex','BP','Cholesterol']

In [59]:
final_data2=pd.get_dummies(df,columns=cols,drop_first=False)

In [60]:
final_data2.head()

Age  Na_to_K   Drug  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  \
0   23   25.355  drugY      1      0        1       0          0   
1   47   13.093  drugC      0      1        0       1          0   
2   47   10.114  drugC      0      1        0       1          0   
3   28    7.798  drugX      1      0        0       0          1   
4   61   18.043  drugY      1      0        0       1          0   

   Cholesterol_HIGH  Cholesterol_NORMAL  
0                 1                   0  
1                 1                   0  
2                 1                   0  
3                 1                   0  
4                 1                   0

In [29]:
final_data=pd.get_dummies(df,columns=cols,drop_first=True)

In [30]:
final_data.head()

Age  Na_to_K   Drug  Sex_M  BP_LOW  BP_NORMAL  Cholesterol_NORMAL
0   23   25.355  drugY      0       0          0                   0
1   47   13.093  drugC      1       1          0                   0
2   47   10.114  drugC      1       1          0                   0
3   28    7.798  drugX      0       0          1                   0
4   61   18.043  drugY      0       1          0                   0

In [42]:
X=final_data.drop('Drug',axis=1)
y=final_data['Drug']

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dt=DecisionTreeClassifier()

In [47]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [48]:
predict=dt.predict(X_test)

In [49]:
from sklearn.metrics import classification_report,confusion_matrix

In [51]:
print(classification_report(y_test,predict))
print(confusion_matrix(y_test,predict))

              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         8
       drugB       1.00      1.00      1.00         4
       drugC       1.00      1.00      1.00         6
       drugX       1.00      1.00      1.00        19
       drugY       1.00      1.00      1.00        29

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66

[[ 8  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 19  0]
 [ 0  0  0  0 29]]


In [52]:
from sklearn.ensemble import RandomForestClassifier

In [53]:
rft=RandomForestClassifier(n_estimators=50)

In [54]:
rft.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [55]:
pred=rft.predict(X_test)

In [56]:
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

              precision    recall  f1-score   support

       drugA       1.00      1.00      1.00         8
       drugB       1.00      1.00      1.00         4
       drugC       1.00      1.00      1.00         6
       drugX       1.00      1.00      1.00        19
       drugY       1.00      1.00      1.00        29

    accuracy                           1.00        66
   macro avg       1.00      1.00      1.00        66
weighted avg       1.00      1.00      1.00        66

[[ 8  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 19  0]
 [ 0  0  0  0 29]]
